export const categories = [
  { label: "All", emoji: "🍾" },
  { label: "Whisky", emoji: "🥃" },
  { label: "Beer", emoji: "🍺" },
  { label: "Wine", emoji: "🍷" },
  { label: "Vodka", emoji: "🍸" },
  { label: "Rum", emoji: "🍹" },
];

export const products = [
  {
    id: 1,
    name: "Glenfiddich 12 Year",
    brand: "Glenfiddich",
    category: "Single Malt Whisky",
    price: "3,499",
    badge: "Bestseller",
    emoji: "🥃",
    description: "Smooth and fruity with hints of pear and oak. Scotland's finest single malt, aged 12 years in American oak and Spanish sherry casks.",
    rating: 4.8,
    stockQty: 24,
    alcoholPercent: 40,
    volume: "750ml",
    images: [],
  },
  {
    id: 2,
    name: "Kingfisher Ultra",
    brand: "United Breweries",
    category: "Premium Beer",
    price: "180",
    badge: null,
    emoji: "🍺",
    description: "Crisp, refreshing lager brewed with the finest hops. India's most loved premium beer with a clean, smooth finish.",
    rating: 4.2,
    stockQty: 50,
    alcoholPercent: 5,
    volume: "650ml",
    images: [],
  },
  {
    id: 3,
    name: "Sula Shiraz",
    brand: "Sula Vineyards",
    category: "Red Wine",
    price: "899",
    badge: "New",
    emoji: "🍷",
    description: "Bold Indian red wine with dark berry notes and a smooth finish. Crafted from hand-picked Shiraz grapes from Nashik Valley.",
    rating: 4.5,
    stockQty: 12,
    alcoholPercent: 13.5,
    volume: "750ml",
    images: [],
  },
  {
    id: 4,
    name: "Absolut Vodka",
    brand: "Absolut",
    category: "Premium Vodka",
    price: "1,299",
    badge: null,
    emoji: "🍸",
    description: "Pure, clean Swedish vodka made from winter wheat. Distilled in a continuous still and blended with water from a deep well in Åhus.",
    rating: 4.6,
    stockQty: 0,
    alcoholPercent: 40,
    volume: "750ml",
    images: [],
  },
  {
    id: 5,
    name: "Old Monk Rum",
    brand: "Mohan Meakin",
    category: "Dark Rum",
    price: "420",
    badge: "Classic",
    emoji: "🍹",
    description: "India's iconic dark rum aged for a minimum of 7 years. Rich, sweet, and unmistakably bold with notes of vanilla and caramel.",
    rating: 4.7,
    stockQty: 8,
    alcoholPercent: 42.8,
    volume: "750ml",
    images: [],
  },
  {
    id: 6,
    name: "Jack Daniel's No.7",
    brand: "Jack Daniel's",
    category: "Tennessee Whiskey",
    price: "2,799",
    badge: null,
    emoji: "🥃",
    description: "Charcoal mellowed drop by drop through 10 feet of sugar maple charcoal for a smooth, distinctive taste. Aged in handcrafted barrels.",
    rating: 4.4,
    stockQty: 0,
    alcoholPercent: 40,
    volume: "750ml",
    images: [],
  },
];
